version: "2"
linters:
  default: none
  enable:
    - errcheck
    - errname
    - errorlint
    - gochecknoglobals
    - gocyclo
    - godox
    - gosec
    - govet
    - ineffassign
    - maintidx
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - thelper
    - unparam
    - unused
  settings:
    errcheck:
      exclude-functions:
        - (io.Writer).Write
        - (io.StringWriter).WriteString
        - (*text/template.Template).Parse
        - (github.com/jackc/pgx/v5.Tx).Rollback
    revive:
      rules:
        - name: receiver-naming
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - gochecknoglobals
          - gocyclo
          - gosec
          - nilnil
          - maintidx
        path: _test\.go
      - path: (.+)\.go$
        text: G115
      - linters: [staticcheck]
        text: "QF1008:"
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: strict
  settings:
    gofumpt:
      # Choose whether to use the extra rules.
      # Default: false
      extra-rules: true
