# Options for analysis running.
run:
  timeout: 15m

linters:
  # # Disable all linters.
  # # Default: false
  disable-all: true
  # # Enable specific linter
  # # https://golangci-lint.run/usage/linters/#enabled-by-default-linters
  enable:
    # defaults
    - revive
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    # extras
    - errname
    - errorlint
    - gci
    - gochecknoglobals
    - gocyclo
    - godox
    - gofumpt
    - gosec
    - maintidx
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - prealloc
    - predeclared
    - revive
    - thelper
    - unparam

linters-settings:
  errcheck:
    exclude-functions:
      - (io.Writer).Write
      - (*text/template.Template).Parse
  revive:
    rules:
      - name: receiver-naming
        disabled: true

issues:
  exclude-rules:
    - path: .
      linters:
        - typecheck
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gochecknoglobals
        - gocyclo
        - dupl
        - gosec
        - nilnil
